### ISSUE TITLE
Objection to FUD in docs ;-)

### ISSUE THREAD

**Issue by pfalcon** [adjih/schc-hackathon#3]
From README:

>   Globally, micropython for unix defines some version of modules with other names like "uXXX", e.g. usocket instead of socket, utime for time, etc.
>
>    micropython for Pycom however, in many cases, keeps the correct names, or implement missing modules

Sorry, Pycom's micropython fork doesn't "keep" "correct names". MicroPython defines API subsets for well-known CPython modules, and consistently names such module "micro &lt;foo>", e.g. utime. That's done on purpose, to allow interested parties to implement *full* functionality of CPython modules, without name clashes. Indeed, there's a project to do just that, e.g. for "time" module: https://github.com/pfalcon/micropython-lib/blob/master/time/time.py

**Comment by adjih** [comment]
Thank you for the correction :) Micropython does it the right way. On our side, we just need to figure out the best way to have the same codebase running on micropython & CPython when the modules of micropython are sufficient.

**Comment by pfalcon** [comment]
Well, MicroPython comes with extensive testsuite, majority of which consists of comparing results of running the same code in MicroPython vs CPython (and only small share - for MicroPython-specific features, comparing with pre-captured output). Here's example: https://github.com/micropython/micropython/blob/master/tests/basics/io_bytesio_ext.py

Btw, this issue from the README was fixed:

~~~
$ ./micropython/ports/unix/micropython -c 'bytearray("aaa", "utf-8")'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: function expected at most 1 arguments, got 2
~~~

(I'm talking here about MicroPython mainline, not sure when/if it'll be propagated to Pycom and other forks.)

**Comment by adjih** [comment]
Thank you for the pointers of tests for MicroPython vs CPython (and the description of the general philosophy). 
It is also excellent news that bytearray behaves like in CPython as we will restart coding for/in the next SCHC Hackathon (Nov3-4).
